baseURL = "https://omarvides.github.io/"
languageCode = "en-us"
title = "Omar Vide's Blog"
publishDir = "docs"

[params]
    accent = "red"
    showBorder = true
    backgroundColor = "white"

[params.widgets]
  recent_articles = true
  categories = true
  tags = true
  tag_cloud = true