baseURL = "https://omarvides.github.io/"
languageCode = "es-us"
title = "Blog de Omar Vides"
publishDir = "public"

[params]
    accent = "red"
    showBorder = true
    backgroundColor = "white"

[params.widgets]
  recent_articles = true
  categories = true
  tags = true
  tag_cloud = true